name: custom_masonry_grid
description: A lightweight, reusable custom masonry grid for Flutter gallery without any external dependencies.
version: 1.0.1

homepage: https://github.com/oxfaysal/custom_masonry_grid

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0


flutter:
  assets:
    - assets/masonry_demo.jpg 